# Generated by Django 3.0 on 2020-01-07 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import moduleone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('pincode', models.IntegerField(verbose_name='pincode')),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='active')),
            ],
            managers=[
                ('allen', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='dt_name')),
                ('spec', models.CharField(max_length=100, verbose_name='dt_spc')),
                ('yrofexp', models.IntegerField()),
                ('salary', models.FloatField(validators=[moduleone.models.checkminsal])),
                ('email', models.EmailField(max_length=100, validators=[moduleone.models.checkclcemail])),
                ('blog', models.SlugField(max_length=300)),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='active')),
            ],
            managers=[
                ('activent', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='pt_name')),
                ('balance', models.FloatField()),
                ('bldgrp', models.CharField(max_length=100)),
                ('diseases', models.CharField(max_length=100)),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='active')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='moduleone.Address')),
                ('doctors', models.ManyToManyField(related_name='patients', to='moduleone.Doctor')),
            ],
            managers=[
                ('allen', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='hs_name')),
                ('active', models.CharField(default='Y', max_length=10, verbose_name='active')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='moduleone.Address')),
            ],
            managers=[
                ('activent', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='moduleone.Hospital'),
        ),
    ]
